import { BarChart3, Briefcase, FileText, GitBranch, LayoutDashboard, Map, Menu, MoreHorizontal, Settings, Target, X } from 'lucide-react';
import { NavLink } from 'react-router-dom';
import { useState } from 'react';
import { useAppContext } from '../../context/AppContext';
import { ProgressBar } from '../ui/ProgressBar';
const main = [{ to: '/', label: 'Dashboard', icon: LayoutDashboard }, { to: '/resume', label: 'Resume Analyzer', icon: FileText }, { to: '/skills', label: 'Skill Assessment', icon: Target }, { to: '/github', label: 'GitHub Analyzer', icon: GitBranch }, { to: '/roadmap', label: 'Career Roadmap', icon: Map }];
const insights = [{ to: '/skill-graph', label: 'Skill Graph', icon: BarChart3 }, { to: '/jobs', label: 'Job Insights', icon: Briefcase }];
function LinkItem({ item, onClick }: { item: typeof main[number]; onClick: () => void }) { const Icon = item.icon; return <NavLink onClick={onClick} to={item.to} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition-all duration-200 ${isActive ? 'bg-[var(--accent-purple)] text-white' : 'text-[var(--text-secondary)] hover:border-l-2 hover:border-[var(--accent-purple)] hover:bg-[var(--bg-card-hover)] hover:text-white'}`}><Icon className="h-5 w-5" />{item.label}</NavLink>; }
export function Sidebar() { const { user, openChatWithPrompt } = useAppContext(); const [open, setOpen] = useState(false); const content = <aside className="flex h-full w-[260px] flex-col border-r border-[var(--border)] bg-[var(--bg-secondary)] p-4"><div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--accent-purple)] font-bold">EP</div><div><h1 className="text-lg font-extrabold">EduPath AI</h1><p className="text-xs text-[var(--text-muted)]">Career intelligence</p></div></div><button className="md:hidden" onClick={() => setOpen(false)}><X /></button></div><p className="mb-2 px-3 text-xs font-bold tracking-widest text-[var(--text-muted)]">MAIN MENU</p><nav className="space-y-1">{main.map((item) => <LinkItem key={item.to} item={item} onClick={() => setOpen(false)} />)}</nav><p className="mb-2 mt-6 px-3 text-xs font-bold tracking-widest text-[var(--text-muted)]">INSIGHTS</p><nav className="space-y-1">{insights.map((item) => <LinkItem key={item.to} item={item} onClick={() => setOpen(false)} />)}</nav><div className="mt-auto space-y-4"><div className="rounded-2xl bg-[var(--bg-card)] p-4"><div className="mb-2 flex justify-between text-sm"><span>Profile Strength</span><span className="stat-number">{user.profileStrength}%</span></div><ProgressBar value={user.profileStrength} color="var(--accent-green)" /><button onClick={() => openChatWithPrompt('Help me complete my EduPath AI profile for a Frontend Developer roadmap.')} className="mt-3 text-sm font-semibold text-[var(--accent-purple-light)]">Complete your profile</button></div><button onClick={() => openChatWithPrompt('What settings should I configure first in my career dashboard?')} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-[var(--text-secondary)] hover:bg-[var(--bg-card-hover)]"><Settings className="h-5 w-5" />Settings</button><div className="flex items-center gap-3 rounded-2xl bg-[var(--bg-card)] p-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[var(--accent-purple)] font-bold">{user.avatar}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{user.name}</p><p className="truncate text-xs text-[var(--text-muted)]">{user.role}</p></div><MoreHorizontal className="h-4 w-4 text-[var(--text-muted)]" /></div></div></aside>;
return <><button onClick={() => setOpen(true)} className="fixed left-4 top-4 z-40 grid h-11 w-11 place-items-center rounded-xl bg-[var(--bg-card)] md:hidden"><Menu /></button><div className="fixed inset-y-0 left-0 z-30 hidden md:block">{content}</div>{open && <div className="fixed inset-0 z-50 bg-black/50 md:hidden"><div className="h-full">{content}</div></div>}</>; }
