import { BookOpen, FileText, Flame, GitBranch, Target } from 'lucide-react';
import { useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { mockRoadmapSteps, mockSkillGaps, mockStats, mockUser } from '../data/mockData';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { ProgressBar } from '../components/ui/ProgressBar';
import { StatCard } from '../components/ui/StatCard';
function Ring({ value }: { value: number }) { return <div className="grid h-40 w-40 place-items-center rounded-full" style={{ background: `conic-gradient(var(--accent-purple) ${value * 3.6}deg, #252840 0deg)` }}><div className="grid h-28 w-28 place-items-center rounded-full bg-[var(--bg-secondary)]"><span className="stat-number text-4xl font-extrabold">{value}%</span></div></div>; }
export function Dashboard() { const navigate = useNavigate(); const gapsRef = useRef<HTMLDivElement>(null); return <div className="space-y-6"><section className="overflow-hidden rounded-3xl border border-[var(--border)] p-6 md:p-8" style={{ background: 'var(--gradient-hero)' }}><div className="grid items-center gap-6 md:grid-cols-[1fr_auto]"><div><p className="mb-3 text-sm font-bold uppercase tracking-widest text-[var(--accent-blue)]">Career readiness dashboard</p><h2 className="max-w-2xl text-3xl font-extrabold md:text-5xl">Your path to becoming a <span className="text-[var(--accent-purple-light)]">{mockUser.targetRole}</span></h2><p className="mt-4 max-w-xl text-[var(--text-secondary)]">Track your resume, portfolio, skill gaps, and weekly learning momentum in one focused career workspace.</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => navigate('/roadmap')}>View your roadmap</Button><Button variant="secondary" onClick={() => gapsRef.current?.scrollIntoView({ behavior: 'smooth' })}>Explore skill gaps</Button></div></div><Ring value={mockUser.roleReadiness} /></div></section>
<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Resume Score" value={`${mockStats.resumeScore}/100`} detail="ATS-ready with quantified impact" badge={`+${mockStats.resumeScoreChange}%`} icon={<FileText />} /><StatCard label="Skills Matched" value={`${mockStats.skillsMatched}/${mockStats.skillsTotal}`} detail={`${mockStats.skillsTotal - mockStats.skillsMatched} skills left`} icon={<Target />} /><StatCard label="GitHub Activity" value={mockStats.githubActivity} detail={`${mockStats.githubCommits} commits this month`} icon={<GitBranch />} /><StatCard label="Learning Streak" value={`${mockStats.learningStreak} days`} detail="Keep the fire going 🔥" icon={<Flame />} /></div>
<div className="grid gap-6 xl:grid-cols-[3fr_2fr]"><Card className="p-6"><h3 className="text-xl font-bold">Career Roadmap Progress</h3><div className="mt-6 grid gap-4 md:grid-cols-4">{mockRoadmapSteps.map((step) => <button key={step.id} onClick={() => navigate('/roadmap')} className="text-left"><div className={`mb-2 grid h-12 w-12 place-items-center rounded-full font-bold ${step.status === 'completed' ? 'bg-[var(--accent-green)] text-black' : step.status === 'in-progress' ? 'bg-[var(--accent-purple)]' : 'bg-[var(--bg-secondary)] text-[var(--text-muted)]'}`}>{step.status === 'completed' ? '✓' : step.id}</div><p className="font-semibold">{step.label}</p><p className="text-xs capitalize text-[var(--text-muted)]">{step.status}</p></button>)}</div><div className="mt-8 rounded-2xl bg-[var(--bg-secondary)] p-5"><div className="mb-3 flex justify-between"><div><h4 className="font-bold">Current focus: Build & Apply</h4><p className="text-sm text-[var(--text-secondary)]">Finish two frontend projects and start tailored applications.</p></div><span className="stat-number">62%</span></div><ProgressBar value={62} color="var(--accent-purple)" /></div></Card>
<Card ref={gapsRef} className="p-6"><h3 className="text-xl font-bold">Top Skill Gaps</h3><div className="mt-4 space-y-3">{mockSkillGaps.map((gap) => <button key={gap.name} onClick={() => navigate('/skills')} className="flex w-full items-center justify-between rounded-xl bg-[var(--bg-secondary)] p-4 text-left transition-all hover:scale-[1.01] hover:bg-[var(--bg-card-hover)]"><div><p className="font-semibold">{gap.name}</p><p className="text-sm text-[var(--text-muted)]">{gap.priority} priority</p></div><Badge tone={gap.status === 'missing' ? 'red' : gap.status === 'partial' ? 'orange' : 'green'}>{gap.status === 'missing' ? 'Missing' : gap.status === 'partial' ? 'Partial' : 'On Track'}</Badge></button>)}</div></Card></div><Button variant="ghost" onClick={() => navigate('/jobs')}><BookOpen className="mr-2 inline h-4 w-4" />Explore matched opportunities</Button></div>; }
