import { useState } from 'react';
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { GitBranch } from 'lucide-react';
import { mockGithubStats } from '../data/mockData';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { useGemini } from '../hooks/useGemini';
const colors = ['#6c63ff', '#00d4aa', '#4fc3f7', '#ff6b35'];
export function GitHubAnalyzer() { const [username, setUsername] = useState(''); const [submitted, setSubmitted] = useState(false); const [commentary, setCommentary] = useState(''); const { generate, isLoading, error } = useGemini(); async function analyzeRole() { const text = await generate(`Analyze this mock GitHub profile for a Frontend Developer role: repos ${mockGithubStats.repos.join(', ')}, TypeScript-heavy language breakdown, score ${mockGithubStats.score}.`); setCommentary(text); } return <div className="space-y-6"><div><h2 className="text-3xl font-extrabold">GitHub Analyzer</h2><p className="mt-2 text-[var(--text-secondary)]">Enter a username to view mock portfolio signals while GitHub API integration is pending.</p></div><Card className="p-5"><form onSubmit={(e) => { e.preventDefault(); setSubmitted(true); }} className="flex flex-col gap-3 md:flex-row"><input value={username} onChange={(e) => setUsername(e.target.value)} className="min-h-11 flex-1 rounded-xl border border-[var(--border)] bg-[var(--bg-secondary)] px-4 outline-none" placeholder="GitHub username" /><Button type="submit"><GitBranch className="mr-2 inline h-4 w-4" />Analyze</Button></form></Card>{submitted && <div className="grid gap-6 xl:grid-cols-2"><Card className="p-5"><h3 className="mb-4 text-xl font-bold">Commit Frequency</h3><ResponsiveContainer width="100%" height={250}><BarChart data={mockGithubStats.commits}><XAxis dataKey="day" stroke="#9499b8" /><YAxis stroke="#9499b8" /><Tooltip /><Bar dataKey="commits" fill="#6c63ff" radius={[8,8,0,0]} /></BarChart></ResponsiveContainer></Card><Card className="p-5"><h3 className="mb-4 text-xl font-bold">Language Breakdown</h3><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={mockGithubStats.languages} dataKey="value" nameKey="name" outerRadius={90} label>{mockGithubStats.languages.map((_, i) => <Cell key={i} fill={colors[i]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></Card><Card className="p-5"><h3 className="text-xl font-bold">Top Repos</h3><div className="mt-4 space-y-3">{mockGithubStats.repos.map((repo) => <div key={repo} className="flex items-center justify-between rounded-xl bg-[var(--bg-secondary)] p-3"><span>{repo}</span><Badge tone="purple">Frontend</Badge></div>)}</div></Card><Card className="p-5"><h3 className="text-xl font-bold">Activity Score</h3><p className="stat-number mt-4 text-5xl font-extrabold text-[var(--accent-green)]">{mockGithubStats.score}/100</p><Button className="mt-5" onClick={analyzeRole} disabled={isLoading}>{isLoading ? 'Generating...' : 'Analyze for Frontend Developer role'}</Button>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}{commentary && <p className="mt-4 text-[var(--text-secondary)]">{commentary}</p>}</Card></div>}</div>; }
