import { FileSearch } from 'lucide-react';
import { useState } from 'react';
import { ResumeUploader } from '../components/resume/ResumeUploader';
import { ResumeFeedback } from '../components/resume/ResumeFeedback';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { LoadingSpinner } from '../components/ui/LoadingSpinner';
import { ProgressBar } from '../components/ui/ProgressBar';
import { useAppContext } from '../context/AppContext';
import { useResumeAnalysis } from '../hooks/useResumeAnalysis';
export function ResumeAnalyzer() { const [resumeText, setResumeText] = useState(''); const [fileName, setFileName] = useState(''); const { setResumeFeedback } = useAppContext(); const { feedback, isLoading, error, status, run } = useResumeAnalysis(); async function analyze() { const result = await run(resumeText); setResumeFeedback(result); } return <div className="space-y-6"><div><h2 className="text-3xl font-extrabold">Resume Analyzer</h2><p className="mt-2 text-[var(--text-secondary)]">Upload or paste your resume for AI-powered ATS scoring and actionable feedback.</p></div><div className="grid gap-6 xl:grid-cols-[1fr_1.2fr]"><Card className="p-6"><ResumeUploader onText={(text, file) => { setResumeText(text); setFileName(file?.name ?? 'Pasted resume'); }} />{fileName && <p className="mt-4 text-sm text-[var(--text-secondary)]">Ready to analyze: {fileName}</p>}{isLoading && <div className="mt-5 rounded-xl bg-[var(--bg-secondary)] p-4"><div className="mb-3 flex items-center gap-2"><LoadingSpinner /> <span>{status}</span></div><ProgressBar value={status.includes('Parsing') ? 35 : status.includes('ATS') ? 68 : 88} color="var(--accent-green)" /></div>}{error && <div className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-red-200"><p>{error}</p><Button className="mt-3" onClick={analyze}>Retry</Button></div>}<Button className="mt-5 w-full" disabled={!resumeText.trim() || isLoading} onClick={analyze}>{isLoading ? 'Analyzing...' : 'Analyze Resume'}</Button></Card><div>{feedback ? <ResumeFeedback feedback={feedback} /> : <Card className="grid min-h-[520px] place-items-center p-8 text-center"><div><div className="mx-auto mb-5 grid h-24 w-24 place-items-center rounded-3xl bg-[var(--accent-purple)]/15"><FileSearch className="h-12 w-12 text-[var(--accent-purple-light)]" /></div><h3 className="text-2xl font-bold">Upload your resume to get AI-powered feedback</h3><p className="mt-2 max-w-md text-[var(--text-secondary)]">Your results will include score, section bars, strengths, improvements, and ATS keywords.</p></div></Card>}</div></div></div>; }
