import { useMemo, useState } from 'react';
import { mockSkills } from '../data/mockData';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { ProgressBar } from '../components/ui/ProgressBar';
import { useAppContext } from '../context/AppContext';
const tabs = ['All', 'Frontend', 'Backend', 'Tools'];
export function SkillAssessment() { const [filter, setFilter] = useState('All'); const [modal, setModal] = useState<string | null>(null); const [value, setValue] = useState(50); const { selfAssessedSkills, updateSkillLevel, openChatWithPrompt } = useAppContext(); const skills = useMemo(() => mockSkills.filter((s) => filter === 'All' || s.category === filter), [filter]); return <div className="space-y-6"><div><h2 className="text-3xl font-extrabold">Skill Assessment</h2><p className="mt-2 text-[var(--text-secondary)]">Review your proficiency and ask EduPath AI for targeted resources.</p></div><div className="flex flex-wrap gap-2">{tabs.map((tab) => <Button key={tab} variant={filter === tab ? 'primary' : 'secondary'} onClick={() => setFilter(tab)}>{tab}</Button>)}</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{skills.map((skill) => { const level = selfAssessedSkills[skill.name] ?? skill.level; return <Card key={skill.name} className="p-5"><div className="flex justify-between"><h3 className="text-lg font-bold">{skill.name}</h3><Badge tone={skill.category === 'Frontend' ? 'purple' : skill.category === 'Backend' ? 'blue' : 'orange'}>{skill.category}</Badge></div><div className="mb-2 mt-5 flex justify-between text-sm"><span>Confidence</span><span className="stat-number">{level}%</span></div><ProgressBar value={level} color={level > 70 ? 'var(--accent-green)' : level > 45 ? 'var(--accent-orange)' : 'var(--accent-purple)'} /><div className="mt-5 flex gap-2"><Button variant="secondary" onClick={() => { setModal(skill.name); setValue(level); }}>Self-assess</Button><Button variant="ghost" onClick={() => openChatWithPrompt(`Suggest learning resources for ${skill.name} for a Frontend Developer student.`)}>Ask AI</Button></div></Card>; })}</div>{modal && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><Card className="w-full max-w-md p-6"><h3 className="text-xl font-bold">Self-assess {modal}</h3><p className="mt-2 text-[var(--text-secondary)]">Set your confidence from 0 to 100.</p><input className="mt-6 w-full accent-[var(--accent-purple)]" type="range" min="0" max="100" value={value} onChange={(e) => setValue(Number(e.target.value))} /><p className="stat-number mt-3 text-center text-3xl font-bold">{value}%</p><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => setModal(null)}>Cancel</Button><Button onClick={() => { updateSkillLevel(modal, value); setModal(null); }}>Save</Button></div></Card></div>}</div>; }
