import { Sparkles, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useAppContext } from '../../context/AppContext';
import { callGemini } from '../../utils/gemini';
import { ChatInput } from './ChatInput';
import { ChatMessage, type Message } from './ChatMessage';
const SYSTEM_PROMPT = `You are EduPath AI, a friendly career guidance assistant for students. You help with: resume tips, skill building, career paths, interview prep, GitHub best practices, job searching strategies. Keep responses concise (2-4 sentences max unless a detailed list is requested). Be encouraging and specific. If asked something outside career/education, politely redirect. Current user context: Targeting Frontend Developer role, 68% role readiness, Resume score 78/100.`;
export function ChatBot() {
  const { chatOpen, setChatOpen, chatDraft, consumeChatDraft } = useAppContext(); const [messages, setMessages] = useState<Message[]>([{ id: 'welcome', role: 'assistant', content: "👋 Welcome to EduPath AI! Ask me about your resume, skill gaps, GitHub portfolio, or next roadmap step.", timestamp: new Date() }]); const [isLoading, setIsLoading] = useState(false); const [error, setError] = useState<string | null>(null); const bottomRef = useRef<HTMLDivElement>(null);
  useEffect(() => bottomRef.current?.scrollIntoView({ behavior: 'smooth' }), [messages, isLoading]);
  useEffect(() => { if (chatOpen && chatDraft) send(consumeChatDraft()); }, [chatOpen, chatDraft]);
  async function send(content: string) { const userMsg = { id: crypto.randomUUID(), role: 'user' as const, content, timestamp: new Date() }; setMessages((m) => [...m, userMsg]); setIsLoading(true); setError(null); try { const reply = await callGemini(content, SYSTEM_PROMPT); setMessages((m) => [...m, { id: crypto.randomUUID(), role: 'assistant', content: reply, timestamp: new Date() }]); } catch (e) { setError(e instanceof Error ? e.message : 'AI request failed'); } finally { setIsLoading(false); } }
  if (!chatOpen) return <button onClick={() => setChatOpen(true)} className="fixed bottom-6 right-6 z-50 grid h-16 w-16 place-items-center rounded-full bg-[var(--accent-purple)] shadow-[var(--shadow-glow)] transition-all hover:scale-105"><span className="absolute h-full w-full animate-ping rounded-full bg-[var(--accent-purple)]/30" /><Sparkles className="relative h-7 w-7" /></button>;
  return <div className="fixed bottom-4 right-4 z-50 flex h-[520px] w-[calc(100vw-2rem)] max-w-[380px] flex-col overflow-hidden rounded-2xl border border-[var(--border-light)] bg-[var(--bg-secondary)] shadow-2xl animate-[fade-in_200ms_ease]"><div className="flex items-center justify-between border-b border-[var(--border)] p-4"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-[var(--accent-purple-light)]" /><h3 className="font-bold">EduPath AI</h3></div><button onClick={() => setChatOpen(false)} className="grid h-9 w-9 place-items-center rounded-xl hover:bg-[var(--bg-card-hover)]"><X className="h-4 w-4" /></button></div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((message) => <ChatMessage key={message.id} message={message} />)}{isLoading && <div className="flex gap-1 rounded-2xl bg-[var(--bg-card)] p-4 w-fit"><span className="typing-dot h-2 w-2 rounded-full bg-[var(--accent-purple-light)]" /><span className="typing-dot h-2 w-2 rounded-full bg-[var(--accent-purple-light)]" /><span className="typing-dot h-2 w-2 rounded-full bg-[var(--accent-purple-light)]" /></div>}{error && <div className="rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200">{error}<button onClick={() => setError(null)} className="ml-2 underline">Dismiss</button></div>}<div ref={bottomRef} /></div><ChatInput onSend={send} disabled={isLoading} /></div>;
}
